gg.jte.development-mode=false
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/chargeback}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chargeback}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chargeback}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
