package com.example.demo.dispute.domain;

public enum FixStrategy {
    NONE,
    MERGE_PER_TYPE,
    COMPRESS_SHOPIFY_IMAGE_IF_IMAGE,
    COMPRESS_STRIPE_PDF,
    REDUCE_TOTAL_SIZE,
    REDUCE_TOTAL_PAGES,
    CONVERT_PDF_TO_PDFA,
    FLATTEN_PDF_PORTFOLIO,
    REMOVE_EXTERNAL_LINKS_PDF,
    MANUAL
}

